language: node_js

node_js:
  - "lts/*"
  - "node"

addons:
  chrome: stable
  firefox: latest
  hosts:
    - admin.localhost
    - api.localhost

jobs:
  allow_failures:
    - os: windows # https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/9#post_10

dist: xenial

services: xvfb

matrix:
  include:
    - os: linux
      script: "npm test"          # testcafe only runs on linux (requires xvfb)
    - os: osx
      script: "npm run test-node"
    - os: windows
      script: "npm run test-node"
